language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_install:
  - composer selfupdate
  - composer install --dev --no-interaction --prefer-source

after_script:
  - bin/test-reporter

notifications:
  email: "demateus@gmail.com"